### ISSUE TITLE
v_dist npz problem in points experiment

### ISSUE THREAD

**Issue by hlhang9527** [nolanwagener/safe_rl#4]
hello, I'm currently stuck in this v_dist problem, is there anything wrong with the original v_dist.npz? thanks for your help.

$ python q_and_v.py --cost_smoothing 0

Traceback (most recent call last):
  File "***/anaconda3/envs/rl/lib/python3.6/site-packages/numpy/lib/npyio.py", line 447, in load
    return pickle.load(fid, **pickle_kwargs)
_pickle.UnpicklingError: invalid load key, 'v'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "q_and_v.py", line 20, in <module>
    v_dists = np.load('npz/v_dists.npz', allow_pickle=True)
  File "/***/anaconda3/envs/rl/lib/python3.6/site-packages/numpy/lib/npyio.py", line 450, in load
    "Failed to interpret file %s as a pickle" % repr(file))
OSError: Failed to interpret file 'npz/v_dists.npz' as a pickle

**Comment by hlhang9527** [comment]
solved by downloading from the source. thanks
