### ISSUE TITLE
plot results

### ISSUE THREAD

**Issue by hlhang9527** [nolanwagener/safe_rl#5]
Dear author,
Thanks for your code and I am stuck in plotting the results:
After I running the scripts, the results are stored in /data. 
the path of date is:

- data
  - point_critic_intv_shaped_cost
      - point_critic_intv_shaped_cost_s0
         - pyt_save
         - config.json
         - progress.tx
         - vars.pkl 

and I am trying to plot by spinning with the error list below, I have no idea how to fix it, could you please help me? thanks!

**python -m safe_rl.run plot data/point_critic_intv_shaped_cost/point_critic_intv_shaped_cost_s0**

with error:  
File "/home/hallie/anaconda3/envs/safe_afv/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/hallie/anaconda3/envs/safe_afv/bin/python', '/home/hallie/Desktop/paper_code/safe_rl/safe_rl/utils/plot.py', 'data/point_critic_intv_shaped_cost/point_critic_intv_shaped_cost_s0']' returned non-zero exit status 1.

and **python -m safe_rl.run plot data/point**

with error 
(safe_afv) ➜  safe_rl git:(icml) ✗ python -m safe_rl.run plot data/point                                                           
Invalid MIT-MAGIC-COOKIE-1 keyPlotting from...

data/point_critic_intv_shaped_cost
data/point_critic_intv_sparse_cost
data/point_csc_shaped_cost
data/point_csc_sparse_cost

Could not read from data/point_critic_intv_shaped_cost/point_critic_intv_shaped_cost_s10/progress.txt
Could not read from data/point_critic_intv_shaped_cost/point_critic_intv_shaped_cost_s0/progress.txt
Could not read from data/point_critic_intv_sparse_cost/point_critic_intv_sparse_cost_s0/progress.txt
Could not read from data/point_critic_intv_sparse_cost/point_critic_intv_sparse_cost_s10/progress.txt

^CTraceback (most recent call last):
  File "/home/hallie/anaconda3/envs/safe_afv/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/hallie/anaconda3/envs/safe_afv/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/hallie/Desktop/paper_code/safe_rl/safe_rl/run.py", line 239, in <module>
    subprocess.check_call(args, env=os.environ)
  File "/home/hallie/anaconda3/envs/safe_afv/lib/python3.6/subprocess.py", line 306, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/home/hallie/anaconda3/envs/safe_afv/lib/python3.6/subprocess.py", line 289, in call
    return p.wait(timeout=timeout)
  File "/home/hallie/anaconda3/envs/safe_afv/lib/python3.6/subprocess.py", line 1477, in wait
    (pid, sts) = self._try_wait(0)
  File "/home/hallie/anaconda3/envs/safe_afv/lib/python3.6/subprocess.py", line 1424, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt

**Comment by hlhang9527** [comment]
this occurs when run several scripts at the same time, solved.
